# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: run-meltingpot-tests

# TODO(jagapiou): don't run tests for all changes?
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        docker-image: ["python:3.7", "python:3.8", "python:3.9"]
    steps:
    - name: Checkout Melting Pot
      uses: actions/checkout@v2
    - name: Run tests in docker
      run: |
        docker run --mount "type=bind,src=$(pwd),dst=/tmp/meltingpot" \
            -w "/tmp/meltingpot" --rm ${{ matrix.docker-image }} /bin/bash install.sh
